### ISSUE TITLE
Subtle bugs

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#1152]
These are some subtle bugs which I found during my inspection. Anyone short of issues may take them up

- [x] Change password back press closes the activity
- [ ] Create copyright fragment leaks memory
- [x] Create copyright fragment goes behind status bar
- [ ] About event share icon remains black after expanding toolbar sometimes 
- [ ] FAQ, track and other lists don't update after creation
- [ ] MainActivity leaks memory

Adding Screenshots later

**Comment by sridharjajoo** [comment]
@Masquerade0097 Kindly reopen this. Other issues also need to be taken care of here.
