### ISSUE TITLE
Lauch app on F-Droid

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#1260]
Parent issue for launching app on F-Droid

- [x] Remove OSS library (#1255)
- [x] Change stetho no-op library (#1261)
- [x] Remove Google Vision API (#1258)
- [x] Remove Google Places API

**Comment by Masquerade0097** [comment]
@mishuvs I'm facing this error while building the app.. Can you please look into it.
`Traceback (most recent call last): File "/usr/bin/fdroid", line 146, in <module> main() File "/usr/bin/fdroid", line 123, in main mod.main() File "/usr/lib/python2.7/dist-packages/fdroidserver/build.py", line 1016, in main + " ".join(metadata_files)) fdroidserver.common.FDroidException: Only one local metadata file allowed! Found: .fdroid.keystorepass.txt .fdroid.keypass.txt`

This is the metadata file.
`Categories:Development
License:GPL-3.0-only
Web Site:https://eventyay.com/
Source Code:https://github.com/fossasia/open-event-orga-app
Issue Tracker:https://github.com/fossasia/open-event-orga-app/issues

Auto Name:Eventyay-Organizer
Summary:Event management app for Organizers using eventyay platform
Description:
eventyay Organizer App provides event management features like:

* Event manager log in and sign up
* Manual attendee check in
* Attendee check in through QR code scan
* Basic event analytics
* Basic ticket management
* Event Detail
* Organizer Detail
.

Repo Type:git
Repo:https://github.com/fossasia/open-event-orga-app

Build:1.0.5alpha,6
    commit=f7907da8a37b5e1814214189d92b4451c413a317
    subdir=app
    gradle=fdroid

Auto Update Mode:None
Update Check Mode:RepoManifest
Current Version:1.0.5alpha
Current Version Code:6`

**Comment by Masquerade0097** [comment]
@mishuvs Please verify the category value in the metadata file.

**Comment by iamareebjamal** [comment]
Category should be `Internet` and `Connectivity`

**Comment by mishuvs** [comment]
@Masquerade0097 I faced that too. It worked for me by removing one of the metadata file manually.

**Comment by Masquerade0097** [comment]
@mishuvs @iamareebjamal The build is now completing successfully and a merge request is sent to fdroid.
Maybe this issue can be closed now.

**Comment by iamareebjamal** [comment]
Our license is also Apache 2, not GPL 3

**Comment by Masquerade0097** [comment]
@iamareebjamal I have added auto update mode with commit tags. Also, our License as given in License.md is GPL 3.0. Open Event Android has their License Apache 2.0.

**Comment by Masquerade0097** [comment]
@iamareebjamal Also, we need to merge development into master with tagged commit before the fdroid PR gets merged, right?

**Comment by iamareebjamal** [comment]
Yes

**Comment by Masquerade0097** [comment]
@iamareebjamal I think it can be closed now.
