### ISSUE TITLE
Add copyright of the event 

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-orga-app#619]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

The API supports [Copyrights](https://open-event-api.herokuapp.com/#copyright) i.e. both addition and it's details. It should be added to the project.
   
**Would you like to work on the issue?**

Yes

**Update**:  Since this is a big issue it's better to do it in multiple issues

- [x] Allow creating copyright and show it. #691 
- [x] Allow updating an existing copyright #737 
- [x] Allow deleting an existing copyright #738 
- [x] Write tests for each feature.

**Comment by icemc** [comment]
Hello, please can I work in this?

**Comment by srv-twry** [comment]
Hello, Actually i intend to work on it. If i am occupied i would definitely pass it to you. Thanks

**Comment by AkshayCHD** [comment]
@srv-twry are you still working on this issue or can i work on this.

**Comment by srv-twry** [comment]
@AkshayCHD Yes, i intend to work on it.

**Comment by srv-twry** [comment]
@iamareebjamal Please suggest where to add the utility to create a copyright for the event and show it once it is created.
PS: The API endpoint of Copyright is separate, so it shouldn't be created at the time of creation of the event IMO.

**Comment by iamareebjamal** [comment]
Yes I agree. There should be an overflow menu for copyright where there should be an option to create or edit it

**Comment by srv-twry** [comment]
@iamareebjamal Where should i show the copyright details ? In the About Event Fragment ?

**Comment by iamareebjamal** [comment]
Yes

**Comment by iamareebjamal** [comment]
@srv-twry Please tell us the status

**Comment by srv-twry** [comment]
@iamareebjamal Apologies, I have been busy lately with the exams and the proposals. 
I will be sending PRs for Updating the copyright followed by deleting the copyright.

**Comment by iamareebjamal** [comment]
Implemented Completely
