### ISSUE TITLE
Implement Sponsors Endpoint

### ISSUE THREAD

**Issue by mishuvs** [fossasia/open-event-orga-app#730]
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

Add Sponsors to the project. The API supports it and hence it should be implemented in the app.

- [x] List all the Sponsors (#900)
- [x] Creation of new Sponsor (#930)
- [x] Updation of existing Sponsor (#934)
- [x] Deletion of a Sponsor (#939 )
- [x] Write tests for each feature (#953)

**Would you like to work on the issue?**
Yes

**Comment by Masquerade0097** [comment]
@mishuvs Are you working on it?

**Comment by mishuvs** [comment]
@Masquerade0097 Yes, I have started.
