### ISSUE TITLE
New release checklist

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-orga-app#809]
- [x] Update README with codacy badge link
- [x] Change package name to com.eventyay.organizer
- [x] Update app version
- [x] Check the app is working correctly
- [x] Merge changes to master branch

**Comment by iamareebjamal** [comment]
@srv-twry @Masquerade0097 @mishuvs @sridharjajoo Updated the check list

**Comment by Masquerade0097** [comment]
@iamareebjamal Working on it.

**Comment by Masquerade0097** [comment]
@iamareebjamal I think it can be closed.
